-- Colinha 2026 - esquema Supabase/PostgreSQL
-- Execute no SQL Editor de um projeto Supabase novo.

create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  election_year smallint not null default 2026,
  uf char(2) not null,
  office text not null,
  candidate_number text not null,
  ballot_name text,
  full_name text,
  party_abbreviation text,
  party_number integer,
  tse_candidate_id text not null,
  registration_status text,
  photo_url text,
  source_generated_at timestamptz,

  candidate_election_status text,
  candidate_urn_status text,
  inserted_in_urn boolean,
  vote_destination text,
  is_substituted boolean,
  substituted_candidate_id text,
  judgement_status text,
  complementary_generated_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint candidates_year_tse_unique unique (election_year, tse_candidate_id)
);

create index if not exists candidates_lookup_idx
  on public.candidates (election_year, uf, office, candidate_number);

create index if not exists candidates_ballot_lookup_idx
  on public.candidates (
    election_year,
    uf,
    office,
    candidate_number,
    inserted_in_urn,
    is_substituted
  );

alter table public.candidates enable row level security;

drop policy if exists "Public read candidates" on public.candidates;
create policy "Public read candidates"
on public.candidates
for select
to anon, authenticated
using (true);

-- Não são criadas policies públicas de INSERT/UPDATE/DELETE.
-- Os scripts administrativos usam a service role, que não deve ir para o frontend.

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'candidate-photos',
  'candidate-photos',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
