'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
const URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://lyagstynyfupldvbzgpb.supabase.co';
const KEY=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'sb_publishable_g3yKs7jTypCIgmXmaJAeUg_PGSkZAhy';
const offices=[
 {id:'depFederal',label:'Deputada ou Deputado Federal',office:'DEPUTADO FEDERAL',digits:4,uf:'PB'},
 {id:'depEstadual',label:'Deputada ou Deputado Estadual',office:'DEPUTADO ESTADUAL',digits:5,uf:'PB'},
 {id:'senador1',label:'Senadora ou Senador — 1ª vaga',office:'SENADOR',digits:3,uf:'PB'},
 {id:'senador2',label:'Senadora ou Senador — 2ª vaga',office:'SENADOR',digits:3,uf:'PB'},
 {id:'governador',label:'Governadora ou Governador',office:'GOVERNADOR',digits:2,uf:'PB'},
 {id:'presidente',label:'Presidenta ou Presidente',office:'PRESIDENTE',digits:2,uf:'BR'}
];
async function lookupParty(c,n){const q=new URLSearchParams({select:'party_abbreviation,party_number',election_year:'eq.2026',uf:`eq.${c.uf}`,office:`eq.${c.office}`,party_number:`eq.${Number(n.slice(0,2))}`,limit:'1'});const r=await fetch(`${URL}/rest/v1/candidates?${q}`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`}});if(!r.ok)throw Error();const a=await r.json();return a[0]||null}
async function lookup(c,n){const q=new URLSearchParams({select:'ballot_name,party_abbreviation,candidate_number,photo_url,tse_candidate_id',election_year:'eq.2026',uf:`eq.${c.uf}`,office:`eq.${c.office}`,candidate_number:`eq.${n}`});const r=await fetch(`${URL}/rest/v1/candidates?${q}`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`}});if(!r.ok)throw Error();return r.json()}
function tone(kind){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=new A(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=kind==='confirm'?880:kind==='correct'?360:620;g.gain.setValueAtTime(.055,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.11);o.start();o.stop(a.currentTime+.11)}catch{}}
export default function Simulator(){
 const [step,setStep]=useState(0),[number,setNumber]=useState(''),[candidate,setCandidate]=useState(null),[party,setParty]=useState(null),[status,setStatus]=useState('idle'),[votes,setVotes]=useState({}),[sound,setSound]=useState(true),[done,setDone]=useState(false);
 const c=offices[step];
 const proportional=c?.office==='DEPUTADO FEDERAL'||c?.office==='DEPUTADO ESTADUAL';
 const duplicateSenator=c?.id==='senador2'&&candidate&&votes.senador1?.tse_candidate_id===candidate.tse_candidate_id;
 const legendVote=proportional&&!!party&&!candidate&&number.length>=2;
 const nullVote=number.length===c?.digits&&status==='none'&&!party;
 const canConfirm=!!candidate||legendVote||nullVote;
 useEffect(()=>{let live=true;setCandidate(null);setParty(null);if(done||!c){setStatus('idle');return}const prop=c.office==='DEPUTADO FEDERAL'||c.office==='DEPUTADO ESTADUAL';if(prop&&number.length>=2){setStatus('loading');const t=setTimeout(async()=>{try{const p=await lookupParty(c,number);if(!live)return;setParty(p);if(number.length===c.digits){const a=await lookup(c,number);if(!live)return;if(a.length===1){setCandidate(a[0]);setStatus('ok')}else setStatus('none')}else setStatus(p?'legend':'idle')}catch{if(live)setStatus('error')}},140);return()=>{live=false;clearTimeout(t)}}if(number.length!==c.digits){setStatus('idle');return}setStatus('loading');const t=setTimeout(()=>lookup(c,number).then(a=>{if(!live)return;if(a.length===1){setCandidate(a[0]);setStatus('ok')}else setStatus('none')}).catch(()=>live&&setStatus('error')),140);return()=>{live=false;clearTimeout(t)}},[number,step,done]);
 function press(n){if(done||number.length>=c.digits)return;if(sound)tone('key');setNumber(v=>v+n)}
 function correct(){if(sound)tone('correct');setNumber('');setCandidate(null);setParty(null);setStatus('idle')}
 function confirm(blank=false){if(!blank&&!canConfirm)return;if(sound)tone('confirm');const vote=blank?{kind:'blank'}:legendVote?{kind:'legend',candidate_number:number,party_abbreviation:party.party_abbreviation,party_number:party.party_number}:duplicateSenator||nullVote?{kind:'null',candidate_number:number,reason:duplicateSenator?'duplicate-senator':'unknown-number'}:{kind:'candidate',...candidate};const next={...votes,[c.id]:vote};setVotes(next);setNumber('');setCandidate(null);setParty(null);if(step===offices.length-1){playFinal();setDone(true)}else setStep(s=>s+1)}
 function playFinal(){if(!sound)return;try{const a=new Audio('/confirma-urna.mp3');a.volume=.9;a.play().catch(()=>{})}catch{}}
 function restart(){setStep(0);setNumber('');setCandidate(null);setParty(null);setVotes({});setDone(false);setStatus('idle')}
 function useInCola(){const p=new URLSearchParams();offices.forEach(o=>{if(votes[o.id]?.kind==='candidate')p.set(o.id,votes[o.id].candidate_number)});window.location.href='/?'+p.toString()}
 if(done)return <main className="simShell"><nav className="topnav"><b>COLINHA 2026</b><div><Link href="/">MONTAR COLA</Link><Link className="active" href="/simulador">SIMULADOR</Link></div></nav><section className="simDone"><div className="simBadge">SIMULADOR EDUCATIVO</div><h1>Simulação concluída</h1><p>Esta experiência serve apenas para treinar a sequência dos cargos. Nenhuma escolha foi gravada.</p><div className="simSummary">{offices.map(o=><div key={o.id}><span>{o.label}</span><strong>{votes[o.id]?.kind==='candidate'?`${votes[o.id].candidate_number} · ${votes[o.id].ballot_name}`:votes[o.id]?.kind==='legend'?`LEGENDA · ${votes[o.id].party_number} · ${votes[o.id].party_abbreviation}`:votes[o.id]?.kind==='null'?`NULO · ${votes[o.id].candidate_number}`:'BRANCO'}</strong></div>)}</div><button className="simPrimary" onClick={useInCola}>USAR NÚMEROS NA MINHA COLA</button><button className="simSecondary" onClick={restart}>RECOMEÇAR SIMULAÇÃO</button></section></main>;
 return <main className="simShell"><nav className="topnav"><b>COLINHA 2026</b><div><Link href="/">MONTAR COLA</Link><Link className="active" href="/simulador">SIMULADOR</Link></div></nav><section className="simWrap"><div className="simIntro"><div><span className="simBadge">SIMULADOR EDUCATIVO</span><h1>Treine a sequência de votação</h1><p>Não é uma urna oficial. Digite apenas números de candidaturas que você já escolheu.</p></div><button className="sound" onClick={()=>setSound(v=>!v)} aria-label={sound?'Desativar sons':'Ativar sons'}>{sound?'SOM ✓':'SOM —'}</button></div><div className="progress">{offices.map((_,i)=><i key={i} className={i<=step?'on':''}/>)}</div><div className="simScreen"><small>{step+1} DE {offices.length}</small><h2>{c.label}</h2><div className="simDigits">{Array.from({length:c.digits},(_,i)=><b key={i}>{number[i]||''}</b>)}</div>{status==='idle'&&<p>Digite {c.digits} dígitos.</p>}{status==='loading'&&<p>Consultando candidatura…</p>}{legendVote&&<div className="legendWarning"><strong>VOTO DE LEGENDA — {party.party_abbreviation}</strong><p>Se confirmar, este voto será registrado para a legenda {party.party_number}.</p></div>}{status==='none'&&!party&&<div className="nullWarning"><strong>VOTO NULO</strong><p>Este número não corresponde a uma candidatura identificada. Se confirmar, este voto será registrado como nulo nesta simulação.</p></div>}{status==='error'&&<p className="simError">Não foi possível consultar agora.</p>}{duplicateSenator&&<div className="nullWarning"><strong>SEGUNDO VOTO NULO</strong><p>Esta candidatura já foi confirmada na 1ª vaga para o Senado. Se confirmar novamente, o segundo voto será considerado nulo.</p></div>}{candidate&&!duplicateSenator&&<div className="simCandidate">{candidate.photo_url?<img src={candidate.photo_url} alt=""/>:<div className="noPhoto">SEM FOTO</div>}<div><strong>{candidate.ballot_name}</strong><span>{candidate.party_abbreviation}</span></div></div>}</div><div className="keypad">{[1,2,3,4,5,6,7,8,9].map(n=><button key={n} onClick={()=>press(String(n))}>{n}</button>)}<button className="blank" onClick={()=>confirm(true)}>BRANCO</button><button onClick={()=>press('0')}>0</button><button className="correct" onClick={correct}>CORRIGE</button><button className="confirm" disabled={!canConfirm} onClick={()=>confirm(false)}>CONFIRMA</button></div><p className="simPrivacy">A simulação acontece no seu navegador. O aplicativo não grava sua sequência de votação.</p></section></main>
}