'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
const URL=process.env.NEXT_PUBLIC_SUPABASE_URL||'https://lyagstynyfupldvbzgpb.supabase.co';
const KEY=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'sb_publishable_g3yKs7jTypCIgmXmaJAeUg_PGSkZAhy';
const offices=[
 {id:'depFederal',label:'Deputada ou Deputado Federal',office:'DEPUTADO FEDERAL',digits:4,uf:'PB'},
 {id:'depEstadual',label:'Deputada ou Deputado Estadual',office:'DEPUTADO ESTADUAL',digits:5,uf:'PB'},
 {id:'senador1',label:'Senadora ou Senador — 1ª vaga',office:'SENADOR',digits:3,uf:'PB'},
 {id:'senador2',label:'Senadora ou Senador — 2ª vaga',office:'SENADOR',digits:3,uf:'PB'},
 {id:'governador',label:'Governadora ou Governador',office:'GOVERNADOR',digits:2,uf:'PB'},
 {id:'presidente',label:'Presidenta ou Presidente',office:'PRESIDENTE',digits:2,uf:'BR'}
];
async function lookup(c,n){const q=new URLSearchParams({select:'ballot_name,party_abbreviation,candidate_number,photo_url,tse_candidate_id',election_year:'eq.2026',uf:`eq.${c.uf}`,office:`eq.${c.office}`,candidate_number:`eq.${n}`});const r=await fetch(`${URL}/rest/v1/candidates?${q}`,{headers:{apikey:KEY,Authorization:`Bearer ${KEY}`}});if(!r.ok)throw Error();return r.json()}
function tone(kind){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=new A(),o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=kind==='confirm'?880:kind==='correct'?360:620;g.gain.setValueAtTime(.055,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.11);o.start();o.stop(a.currentTime+.11)}catch{}}
export default function Simulator(){
 const [step,setStep]=useState(0),[number,setNumber]=useState(''),[candidate,setCandidate]=useState(null),[status,setStatus]=useState('idle'),[votes,setVotes]=useState({}),[sound,setSound]=useState(true),[done,setDone]=useState(false);
 const c=offices[step];
 useEffect(()=>{let live=true;setCandidate(null);if(done||!c||number.length!==c.digits){setStatus('idle');return}setStatus('loading');const t=setTimeout(()=>lookup(c,number).then(a=>{if(!live)return;if(a.length===1){setCandidate(a[0]);setStatus('ok')}else setStatus('none')}).catch(()=>live&&setStatus('error')),140);return()=>{live=false;clearTimeout(t)}},[number,step,done]);
 function press(n){if(done||number.length>=c.digits)return;if(sound)tone('key');setNumber(v=>v+n)}
 function correct(){if(sound)tone('correct');setNumber('');setCandidate(null);setStatus('idle')}
 function confirm(blank=false){if(!blank&&(!candidate||status!=='ok'))return;if(sound)tone('confirm');const next={...votes,[c.id]:blank?null:candidate};setVotes(next);setNumber('');setCandidate(null);if(step===offices.length-1)setDone(true);else setStep(s=>s+1)}
 function restart(){setStep(0);setNumber('');setCandidate(null);setVotes({});setDone(false);setStatus('idle')}
 function useInCola(){const p=new URLSearchParams();offices.forEach(o=>{if(votes[o.id])p.set(o.id,votes[o.id].candidate_number)});window.location.href='/?'+p.toString()}
 if(done)return <main className="simShell"><nav className="topnav"><b>COLINHA 2026</b><div><Link href="/">MONTAR COLA</Link><Link className="active" href="/simulador">SIMULADOR</Link></div></nav><section className="simDone"><div className="simBadge">SIMULADOR EDUCATIVO</div><h1>Simulação concluída</h1><p>Esta experiência serve apenas para treinar a sequência dos cargos. Nenhuma escolha foi gravada.</p><div className="simSummary">{offices.map(o=><div key={o.id}><span>{o.label}</span><strong>{votes[o.id]?`${votes[o.id].candidate_number} · ${votes[o.id].ballot_name}`:'BRANCO'}</strong></div>)}</div><button className="simPrimary" onClick={useInCola}>USAR NÚMEROS NA MINHA COLA</button><button className="simSecondary" onClick={restart}>RECOMEÇAR SIMULAÇÃO</button></section></main>;
 return <main className="simShell"><nav className="topnav"><b>COLINHA 2026</b><div><Link href="/">MONTAR COLA</Link><Link className="active" href="/simulador">SIMULADOR</Link></div></nav><section className="simWrap"><div className="simIntro"><div><span className="simBadge">SIMULADOR EDUCATIVO</span><h1>Treine a sequência de votação</h1><p>Não é uma urna oficial. Digite apenas números de candidaturas que você já escolheu.</p></div><button className="sound" onClick={()=>setSound(v=>!v)} aria-label={sound?'Desativar sons':'Ativar sons'}>{sound?'SOM ✓':'SOM —'}</button></div><div className="progress">{offices.map((_,i)=><i key={i} className={i<=step?'on':''}/>)}</div><div className="simScreen"><small>{step+1} DE {offices.length}</small><h2>{c.label}</h2><div className="simDigits">{Array.from({length:c.digits},(_,i)=><b key={i}>{number[i]||''}</b>)}</div>{status==='idle'&&<p>Digite {c.digits} dígitos.</p>}{status==='loading'&&<p>Consultando candidatura…</p>}{status==='none'&&<p className="simError">Número não identificado na base.</p>}{status==='error'&&<p className="simError">Não foi possível consultar agora.</p>}{candidate&&<div className="simCandidate">{candidate.photo_url?<img src={candidate.photo_url} alt=""/>:<div className="noPhoto">SEM FOTO</div>}<div><strong>{candidate.ballot_name}</strong><span>{candidate.party_abbreviation}</span></div></div>}</div><div className="keypad">{[1,2,3,4,5,6,7,8,9].map(n=><button key={n} onClick={()=>press(String(n))}>{n}</button>)}<button className="blank" onClick={()=>confirm(true)}>BRANCO</button><button onClick={()=>press('0')}>0</button><button className="correct" onClick={correct}>CORRIGE</button><button className="confirm" disabled={!candidate} onClick={()=>confirm(false)}>CONFIRMA</button></div><p className="simPrivacy">A simulação acontece no seu navegador. O aplicativo não grava sua sequência de votação.</p></section></main>
}